name: 🔨 Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        deno-version: [1.0.0, 1.0.1, 1.0.2, 1.0.3]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Use Deno Version ${{ matrix.deno-version }}
      uses: denolib/setup-deno@master
      with:
        deno-version: ${{ matrix.deno-version }}
    - name: Lint Module
      run: deno fmt --check
    - name: Build Module
      run: deno run --reload mod.ts
    - name: Test Module
      run: deno test --allow-net
